routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\VariantController;
use App\Http\Controllers\ProductImageController;
use App\Http\Controllers\ProductCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('welcome');
});

Route::resource('/variant', VariantController::class);
Route::resource('/product-category', ProductCategoryController::class);
Route::resource('/product-image', ProductImageController::class);
Route::resource('/product', ProductController::class);

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg bg-danger navbar-dark">
   <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
         <ul class="navbar-nav">
            <li class="nav-item">
               <a class="nav-link {{ Request::is('variant') ? 'active' : '' }}" href="{{ route('variant.index') }}">Variants</a>
            </li>
            <li class="nav-item">
               <a class="nav-link {{ Request::is('product-category') ? 'active' : '' }}" href="{{ route('product-category.index') }}">Product Categories</a>
            </li>
            <li class="nav-item">
               <a class="nav-link {{ Request::is('product-image') ? 'active' : '' }}" href="{{ route('product-image.index') }}">Product Image</a>
            </li>
            <li class="nav-item">
               <a class="nav-link {{ Request::is('product') ? 'active' : '' }}" href="{{ route('product.index') }}">Product</a>
            </li>
         </ul>
      </div>
   </div>
</nav>