routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\VariantController;
use App\Http\Controllers\ProductImageController;
use App\Http\Controllers\ProductCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('welcome');
});

Route::resource('/variant', VariantController::class);
Route::resource('/product-category', ProductCategoryController::class);
Route::resource('/product-image', ProductImageController::class);
Route::resource('/product', ProductController::class);

app/Models/ProductCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function product()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/ProductCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductCategory;
use Illuminate\Http\Request;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('product_categories.index', [
            'ProductCategory' => ProductCategory::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product_categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name_category' => 'required'
        ]);

        ProductCategory::create($validate);
        return redirect()->route('product-category.index')->with('success','New data created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function show(ProductCategory $productCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductCategory $productCategory)
    {
        return view('product_categories.edit', [
            'productCategory' => $productCategory
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ProductCategory $productCategory)
    {
        $rules = [
            'name_category' => 'required'
        ];

        $validatedData = $request->validate($rules);

        ProductCategory::where('id', $productCategory->id)->update($validatedData);

        return redirect()->route('product-category.index')->with('success','Updated data successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProductCategory $productCategory)
    {
        $productCategory->delete();

        return redirect()->route('product-category.index')->with('success','Deleted data successfully');
    }
}

resources/views/product_categories/create.blade.php
@extends('main_menu.main')

@section('container')
<div class="container-fluid px-4">
   <h1 class="mt-4">Create New Product Category</h1>
   <div class="card col-lg-8" style="padding: 13px; max-width: 30rem; box-shadow: 6px 8px rgb(0 0 0 / 4%); border: 1">
      <form action="{{ route('product-category.store') }}" method="POST" class="mb-3" enctype="multipart/form-data">
      @csrf
      <div class="mb-3">
         <label for="name_category" class="form-label">Name Category</label>
         <input type="text" class="form-control @error('name_category') is-invalid @enderror" id="name_category" name="name_category" placeholder="name category" required>
         @error('name_category')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
         <button type="submit" class="btn btn-primary">Create New Product Category</button>
      </form>
   </div>   
</div>
@endsection

resources/views/product_categories/edit.blade.php
@extends('main_menu.main')

@section('container')
<div class="container-fluid px-4">
   <h1 class="mt-4">Edit Product Category</h1>
   <div class="card col-lg-8" style="padding: 13px; max-width: 30rem; box-shadow: 6px 8px rgb(0 0 0 / 4%); border: 1">
      <form action="{{ route('product-category.update', $productCategory->id) }}" method="POST" class="mb-3" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="mb-3">
         <label for="name_category" class="form-label">Name Category</label>
         <input type="text" class="form-control @error('name_category') is-invalid @enderror" id="name_category" name="name_category" placeholder="name category" required value="{{ $productCategory->name_category }}">
         @error('name_category')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
         <button type="submit" class="btn btn-primary">Edit Product Category</button>
      </form>
   </div>   
</div>
@endsection

resources/views/product_categories/index.blade.php
@extends('main_menu.main')

@section('container')
<div class="table-responsive col-lg-6">
  <a href="{{ route('product-category.create') }}" class="btn btn-primary mb-3">Create New Variant</a>
  @if (session()->has('success'))
    <div class="alert alert-success col-lg-6 alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      {{ session('success') }}
    </div>
  @endif
    <table class="table table-bordered">
      <thead>
         <tr>
            <th scope="col">No</th>
            <th scope="col">Name Category</th>
            <th scope="col">Action</th>
         </tr>
      </thead>
      <tbody>
         @foreach ($ProductCategory as $productcategory)
         <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $productcategory->name_category }}</td>
            <td>
               <a href="{{ route('product-category.edit', $productcategory->id) }}" class="badge bg-warning">
                  <span data-feather="edit">Edit</span>
               </a>
               <form action="{{ route('product-category.destroy', $productcategory->id) }}" method="POST" class="d-inline">
                  @method('delete')
                  @csrf
                  <button class="badge bg-danger border-0"><span data-feather="x-circle">Delete</span></button>
               </form>
            </td>
         </tr>
        @endforeach
      </tbody>
    </table>
</div>
@endsection