routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\VariantController;
use App\Http\Controllers\ProductImageController;
use App\Http\Controllers\ProductCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('welcome');
});

Route::resource('/variant', VariantController::class);
Route::resource('/product-category', ProductCategoryController::class);
Route::resource('/product-image', ProductImageController::class);
Route::resource('/product', ProductController::class);

app/Models/Variant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Variant extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function product()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/VariantController.php
<?php

namespace App\Http\Controllers;

use App\Models\Variant;
use Illuminate\Http\Request;

class VariantController extends Controller
{
    public function index()
    {
        return view('variants.index', [
            'variants' => Variant::all()
        ]);
    }

    public function create()
    {
        return view('variants.create');
    }

    public function store(Request $request) 
    {
        $validate = $request->validate([
            'size' => 'required',
            'color' => 'required',
        ]);

        Variant::create($validate);
        return redirect()->route('variant.index')->with('success','New data created successfully');
    }

    public function edit(Variant $variant)
    {
        return view('variants.edit', [
            'variant' => $variant
        ]); 
    }

    public function update(Request $request, Variant $variant)
    {
        $rules = [
            'size' => 'required',
            'color' => 'required'
        ];

        $validatedData = $request->validate($rules);

        Variant::where('id', $variant->id)->update($validatedData);

        return redirect()->route('variant.index')->with('success','Updated data successfully');
    }

    public function destroy(Variant $variant)
    {
        $variant->delete();

        return redirect()->route('variant.index')->with('success','Deleted data successfully');
    }
}

resources/views/variants/create.blade.php
@extends('main_menu.main')

@section('container')
<div class="container-fluid px-4">
   <h1 class="mt-4">Create New Variant</h1>
   <div class="card col-lg-8" style="padding: 13px; max-width: 30rem; box-shadow: 6px 8px rgb(0 0 0 / 4%); border: 1">
      <form action="{{ route('variant.store') }}" method="POST" class="mb-3" enctype="multipart/form-data">
      @csrf
      <div class="mb-3">
         <label for="size" class="form-label">Size</label>
         <input type="text" class="form-control @error('size') is-invalid @enderror" id="size" name="size" placeholder="Size" required>
         @error('size')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
      <div class="mb-3">
         <label for="color" class="form-label">Color</label>
         <input type="text" class="form-control @error('color') is-invalid @enderror" id="color" name="color" placeholder="Color" required>
         @error('color')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
         <button type="submit" class="btn btn-primary">Create New Variant</button>
      </form>
   </div>   
</div>
@endsection

resources/views/variants/edit.blade.php
@extends('main_menu.main')

@section('container')
<div class="container-fluid px-4">
   <h1 class="mt-4">Create Edit Variant</h1>
   <div class="card col-lg-8" style="padding: 13px; max-width: 30rem; box-shadow: 6px 8px rgb(0 0 0 / 4%); border: 1">
      <form action="{{ route('variant.update', $variant->id) }}" method="POST" class="mb-3" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="mb-3">
         <label for="size" class="form-label">Size</label>
         <input type="text" class="form-control @error('size') is-invalid @enderror" id="size" name="size" placeholder="Size" required value="{{ $variant->size }}">
         @error('size')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
      <div class="mb-3">
         <label for="color" class="form-label">Color</label>
         <input type="text" class="form-control @error('color') is-invalid @enderror" id="color" name="color" placeholder="Color" required value="{{ $variant->color }}">
         @error('color')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
         <button type="submit" class="btn btn-primary">Create Edit Variant</button>
      </form>
   </div>   
</div>
@endsection

resources/views/variants/index.blade.php
@extends('main_menu.main')

@section('container')
<div class="table-responsive col-lg-6">
  <a href="{{ route('variant.create') }}" class="btn btn-primary mb-3">Create New Variant</a>
  @if (session()->has('success'))
    <div class="alert alert-success col-lg-6 alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      {{ session('success') }}
    </div>
  @endif
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">Size</th>
          <th scope="col">Color</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($variants as $variant)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $variant->size }}</td>
            <td>{{ $variant->color }}</td>
            <td>
              <a href="{{ route('variant.edit', $variant->id) }}" class="badge bg-warning">
                <span data-feather="edit">Edit</span>
              </a>
              <form action="{{ route('variant.destroy', $variant->id) }}" method="POST" class="d-inline">
                @method('delete')
                @csrf
                <button class="badge bg-danger border-0"><span data-feather="x-circle">Delete</span></button>
              </form>
            </td>
        </tr>
        @endforeach
      </tbody>
    </table>
</div>
@endsection