routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\VariantController;
use App\Http\Controllers\ProductImageController;
use App\Http\Controllers\ProductCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('welcome');
});

Route::resource('/variant', VariantController::class);
Route::resource('/product-category', ProductCategoryController::class);
Route::resource('/product-image', ProductImageController::class);
Route::resource('/product', ProductController::class);

app/Models/ProductImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductImage extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function product()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/ProductImageController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductImage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('product_images.index', [
            'ProductImage' => ProductImage::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product_images.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name_image' => 'required',
            'image' => 'required|image|file|max:2024'
        ]);

        if($request->file('image') ) {
            $validatedData['image'] = $request->file('image')->store('product-images');
        }

        ProductImage::create($validatedData);
        return redirect()->route('product-image.index')->with('success','New data created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ProductImage  $productImage
     * @return \Illuminate\Http\Response
     */
    public function show(ProductImage $productImage)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ProductImage  $productImage
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductImage $productImage)
    {
        return view('product_images.edit', [
            'productimage' => $productImage
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ProductImage  $productImage
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ProductImage $productImage)
    {
        $rules = [
            'name_image' => 'required',
            'image' => 'required|image|file|max:2024'
        ];
        $validatedData = $request->validate($rules);
        if($request->file('image')){
            $validatedData['image'] = $request->file('image')->store('product-images');
            Storage::delete($productImage->image);
        }

        ProductImage::where('id', $productImage->id)->update($validatedData);
        return redirect()->route('product-image.index')->with('success','Updated data successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ProductImage  $productImage
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProductImage $productImage)
    {
        Storage::delete($productImage->image);

        $productImage->delete();
        return redirect()->route('product-image.index')->with('success','Deleted data successfully');
    }
}

resources/views/product_images/create.blade.php
@extends('main_menu.main')

@section('container')
<div class="container-fluid px-4">
   <h1 class="mt-4">Create New Product Image</h1>
   <div class="card col-lg-8" style="padding: 13px; max-width: 30rem; box-shadow: 6px 8px rgb(0 0 0 / 4%); border: 1">
      <form action="{{ route('product-image.store') }}" method="POST" class="mb-3" enctype="multipart/form-data">
      @csrf
      <div class="mb-3">
         <label for="name_image" class="form-label">Name Image</label>
         <input type="text" class="form-control @error('name_image') is-invalid @enderror" id="name_image" name="name_image" placeholder="name image" required>
         @error('name_image')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
      <div class="mb-3">
         <label for="image" class="form-label">Upload Image</label>
         <input class="form-control @error('image') is-invalid @enderror" type="file" id="image" name="image">
         @error('image')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
         <button type="submit" class="btn btn-primary">Create New Product Image</button>
      </form>
   </div>   
</div>
@endsection

resources/views/product_images/edit.blade.php
@extends('main_menu.main')

@section('container')
<div class="container-fluid px-4">
   <h1 class="mt-4">Edit Product Image</h1>
   <div class="card col-lg-8" style="padding: 13px; max-width: 30rem; box-shadow: 6px 8px rgb(0 0 0 / 4%); border: 1">
      <form action="{{ route('product-image.update', $productimage->id) }}" method="POST" class="mb-3" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="mb-3">
         <label for="name_image" class="form-label">Name Image</label>
         <input type="text" class="form-control @error('name_image') is-invalid @enderror" id="name_image" name="name_image" placeholder="name image" required value="{{ $productimage->name_image }}">
         @error('name_image')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
      <div class="mb-3">
         <label for="image" class="form-label">Upload Image</label>
         <input class="form-control @error('image') is-invalid @enderror" type="file" id="image" name="image">
         @error('image')
            <div class="invalid-feedback">
               {{ $message }}
            </div>
         @enderror
      </div>
         <button type="submit" class="btn btn-primary">Edit Product Image</button>
      </form>
   </div>   
</div>
@endsection

resources/views/product_images/index.blade.php
@extends('main_menu.main')

@section('container')
<div class="table-responsive col-lg-6">
  <a href="{{ route('product-image.create') }}" class="btn btn-primary mb-3">Create New Product Image</a>
  @if (session()->has('success'))
    <div class="alert alert-success col-lg-6 alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      {{ session('success') }}
    </div>
  @endif
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">Name Image</th>
          <th scope="col">Image</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($ProductImage as $productimage)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $productimage->name_image }}</td>
            <td class="text-center">
              <img src="{{ asset('storage/'.$productimage->image) }}" class="rounded" style="width: 100px">
            </td>
            <td>
              <a href="{{ route('product-image.edit', $productimage->id) }}" class="badge bg-warning">
                <span data-feather="edit">Edit</span>
              </a>
              <form action="{{ route('product-image.destroy', $productimage->id) }}" method="POST" class="d-inline">
                @method('delete')
                @csrf
                <button class="badge bg-danger border-0"><span data-feather="x-circle">Delete</span></button>
              </form>
            </td>
        </tr>
        @endforeach
      </tbody>
    </table>
</div>
@endsection